/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#ffffff",
        "on-tertiary": "#2e3037",
        "surface-variant": "#323537",
        "surface": "#101415",
        "primary-fixed-dim": "#ebb2ff",
        "tertiary": "#c4c6cf",
        "outline": "#9d8ba0",
        "outline-variant": "#504254",
        "background": "#101415",
        "on-primary": "#520072",
        "on-surface": "#e0e3e5",
        "surface-container-low": "#191c1e",
        "surface-container": "#1d2022",
        "surface-container-highest": "#323537",
        "surface-bright": "#363a3b",
        "on-secondary-container": "#005669",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#74767e",
        "inverse-surface": "#e0e3e5",
        "surface-tint": "#ebb2ff",
        "on-tertiary-fixed-variant": "#44474e",
        "secondary-fixed-dim": "#3cd7ff",
        "inverse-on-surface": "#2d3133",
        "surface-container-high": "#272a2c",
        "on-primary-fixed-variant": "#74009f",
        "on-background": "#e0e3e5",
        "surface-dim": "#101415",
        "primary": "#ebb2ff",
        "on-tertiary-fixed": "#191c22",
        "tertiary-fixed": "#e1e2eb",
        "on-secondary-fixed-variant": "#004e5f",
        "secondary": "#a2e7ff",
        "surface-container-lowest": "#0b0f10",
        "tertiary-fixed-dim": "#c4c6cf",
        "on-primary-fixed": "#320047",
        "primary-container": "#bc13fe",
        "on-secondary-fixed": "#001f27",
        "error": "#ffb4ab",
        "secondary-container": "#00d2fd",
        "on-error": "#690005",
        "inverse-primary": "#9800d0",
        "on-secondary": "#003642",
        "on-primary-container": "#ffffff",
        "on-surface-variant": "#d4c0d7",
        "secondary-fixed": "#b4ebff",
        "error-container": "#93000a",
        "primary-fixed": "#f8d8ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "8px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        "container-max": "1280px"
      },
      fontFamily: {
        "display-lg": ["Sora"],
        "mono-label": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg-mobile": ["Sora"],
        "label-caps": ["Inter"],
        "headline-md": ["Sora"],
        "body-md": ["Inter"],
        "headline-lg": ["Sora"]
      }
    },
  },
  plugins: [],
}
